const demoEfforts = [
  {
    athleteId: 1075670,
    date: "2019-11-21T17:32:36Z",
    id: 71581777284,
    name: "Stough Canyon Mountain Way Climb",
    segmentId: 957951,
    rank: 1,
    line:
      "wrvoExtbqUOFOPe@\\QDc@?OCU@c@CS?MEy@IECk@Ba@Ce@H]LUL_@\\OV[`AEp@St@INKDK?OCQOO_@AQLw@j@{A~@cBRQ^Qz@SXQx@W^CBI@W?e@O[_@MUAg@KeBJ[FKNi@TiApA[fAo@hAWx@KNOJSXq@b@WHY?CCKe@Dm@Pq@Vg@Lq@N]V[~@mBt@kA`AeAn@]ZWJW?OAa@EMICY@q@Ny@LUHi@Ze@Rs@n@GHKZcAfBk@t@s@zAYRQHG?eA]SSEO",
  },
  {
    athleteId: 1075670,
    date: "2019-09-07T15:46:12Z",
    id: 67255052510,
    name: "2012 Fall Century 2nd to 3rd Reststop",
    segmentId: 2339618,
    rank: 1,
    line:
      "ytgfF|rntUiBuDgA{CwAeFyCoLk@mCaB}IeAmG]sCAk@?m@HyAXsA^kAdAeCzEsHd@kANk@Li@NuB?q@Cq@KmAMq@Sq@Yo@]k@{DsE_C{DcA_Ai@Qk@GWAcBDeC?sAJ}MjDy@Ny@F[A[C[IYOo@k@c@}@QgAAmAPgA`@}@TYp@i@lGcDt@c@fA}@d@u@\\{@d@aBb@mA~@eBdDsF^q@x@gBXs@dAcD~@_ClDgIdAuB`C{DhF{IzAwB|GyIdBsC\\u@~@}BpJaXr@eCTsAFk@FaBNuL@yDCyBeFarASuDOkCc@qFiAoKk@cHqJqpAO{AgCwQWsCMmCAaAA{CHgCH{AXwCxBuNr@mFj@oCZqBv@kGRmBb@wHBsBQkGQgCcB_MuAsLOs@_@eAaDqHiJeUgOsYsGmN}EqLwBaFyKqXqAaCkNkTkAwBm@aBeB_HmAkFiAwEmUaz@aCcJoAgEe@eAeBeC]s@sBmGm@sAq@iAsB{BgAgBg@o@aCeCmCmDe@w@oAuCc@{@uBaDeAoAoBaDeCaD_AwAoAoCc@mAeAeDe@mAsAkCiBeDy@aB[eAGkABa@VaAL_@nGyMlDcIdFyLhTyj@`FgMvDeKrIuTfBaF|@uB~CgI~Mk^jGeQlDiJbFyM~GeRjGiPlBqFfFgNpHkSrHeSda@mgA`I_TdAcDfF{NzBcG~@yBnA{BxDsFdJ{MzCiEpB{Cd@w@vEaHdJwMnHyKnLwPjAqBtDmHlHaNlEcIjAkB|@u@hL{E~@e@tCeA`CeApCeAfMeFp[wMzL{EhMgFlEmBpGeClB_AdDiAbFwBtAg@nFyB|CsAxAi@zGsCrFuBzZgMvOiGzi@wTxMqFt[oMtUsJtOiG|^gOnNwFl@YjGeCb\\{MxOiG|_@uOxKmEbBy@r@y@l@yA",
  },
  {
    athleteId: 1075670,
    date: "2017-07-25T18:00:37Z",
    id: 27110160543,
    name: "Bowles to Union E side",
    segmentId: 1314761,
    rank: 1,
    line:
      "ccxpF|l_`SO}@Sy@Ym@cA}Aa@w@gBqF]q@i@m@{AqAm@_@_By@yCuAuA_AcBq@s@a@s@g@sAqAq@_@w@M_AW}@_@wBwA_A_@cAMeA@cAX{@b@gBtAaBpBm@l@{@d@y@ZaAPcAFeAS{@k@m@u@]aAq@aC]{@e@s@oBmCqAwAk@g@k@Ww@Es@OyC_A",
  },
  {
    athleteId: 1075670,
    date: "2013-06-19T01:10:11Z",
    id: 13376864021,
    name: "Santa Monica to State",
    segmentId: 4053574,
    rank: 1,
    line:
      "{t~pE|vpxUZp@VlC@p@AVObBwCzWiB|Om@xEC~AGdRAvAIjBMfBY~BYbBk@tBq@lBu@xAeAhBuChE[^cAfAgLjLmAzAw@bBqE~KkAlC}@zAu@`AaGdHaBdBUZy@`Bq@bBa@vAOv@QlB_AbQc@jKEpA?nABxBDhAj@`IGV@RBRLPRfD?bAQ~DAd@Dh@f@fHn@~Gt@nDLlA@nAO|EYrCa@vBkAnFm@zBoBlFUx@QhAGjA?h@p@lIDtBCtBIlBQhBWdBWrAi@lBeEhMc@dCwBtQYdBm@hCcFvPy@|CUfBIzASR?p@PR@bAJbBXzBDv@?d@Cv@YrCp@IV\\PdA^`DXjBKJFdCApBKtCKvAcB~NUpCA^OpAKLK\\A`@IdBa@nDIrAk@fARp@~AfJJz@PnBjAhR\\`LBjCCjCWlKS|COvAa@`C{@jDaCdIUn@{@jBIVEh@A`@@tGVfITpE\\zB@^FZHL`BxJTdB\\~C@HNRDVBn@DTGhAHxAXlAVp@Np@XhBDxA?v@GxBCPA~@E`@?zAEt@BjBWtBEh@S|@YzBEbB@XCp@ClEDh@AfAK`BE^U~@mBpFMNYJi@GMLEH?TVr@HJ?NEZ_@bACPG\\@ZRjARn@\\n@v@jBrAlCNNd@^z@d@tA`Al@p@`@dABRVr@Ll@ThCDfA@bAHrBAn@FzAAl@HnARl@LTX^|@v@bBx@b@P\\Fp@`@Zj@JVHb@HlBf@xBRtCZfBVbDNz@@j@C\\Dx@En@K~C@fABx@N|Ar@jGNjALp@?VHZb@jD`@jETnBj@vFN|@Fx@RbALpAPx@FpANz@B~@ZhDBz@Hh@Ff@@P?ZJf@@PETHh@A|A?h@Hf@ATLbBD|@L~@BrAFn@@d@Hz@B~@XnBHxAPxADh@TtAh@dB\\x@Nf@\\VnIdJ",
  },
  {
    athleteId: 1075670,
    date: "2019-01-29T15:34:06Z",
    id: 53257592144,
    name: "Tuna descent - the most technical parts",
    segmentId: 7756055,
    rank: 1,
    line:
      "md{nErn{rUXc@h@Wf@a@h@Wj@Bh@Q\\g@h@YROXe@PKRBXh@HZLxBFXHVLNNFNGHMGiAHw@J{BF]NYVMv@Cr@IVIj@a@h@m@PWLYF[Bq@FSNKbACTGh@a@NSJYFo@NMREb@DPGj@aA\\u@R[h@i@Vm@LOPGR?tA`@\\ZLFL@JIDOAk@I_AFMNGR@RD`Ab@V@VCh@WVEVBz@PPCJMHk@?YEYBULQh@YTQbBeCX[vBiBxAcAt@Y|AMNILQ`A{CT}@D_@N{A@YG[IYEy@H[RUp@a@TSNYF]@aAF[\\_A?WEUKMOCQLSl@OVe@h@",
  },
  {
    athleteId: 1075670,
    date: "2016-06-22T19:32:50Z",
    id: 31047707456,
    name: "Mira Vista Ave Climb",
    segmentId: 1278451,
    rank: 1,
    line:
      "kkcqEreryU_CpDiHnKmBzCwChEwEpHgBfCe@r@a@La@WoCyCCi@D_FKa@SIYN_B`CQHYO]]M_@@_ERsAEm@q@_@_@[?UXcABw@k@qF_AyG@aACoBq@sJ",
  },
  {
    athleteId: 1075670,
    date: "2019-01-03T00:46:33Z",
    id: 51741169341,
    name: "WLAC Circuit",
    segmentId: 1603917,
    rank: 1,
    line:
      "s~onE~crqUP[b@yBLsCJyDVqDBgBLmAAsA?]Da@?a@Cu@QyBKQOGuA@i@BWDe@AuCLyDDmCL}DJeADYFcA^}@p@QTMZ}AbC]f@{@bAu@dAe@dBFf@ZXjEnAbC|@hDvApBf@~DvAxAZf@NrALLHx@ZlAx@XZx@VV[BK",
  },
  {
    athleteId: 1075670,
    date: "2016-09-01T21:52:21Z",
    id: 17095894031,
    name: "Florida westbound: Colorado Blvd to Steele",
    segmentId: 8789056,
    rank: 1,
    line: "wyfqFtgo_SFfFCjCDfHAdA@~EAxABnGChDDjA?`BAbC",
  },
  {
    athleteId: 1075670,
    date: "2016-11-09T20:12:00Z",
    id: 18863624585,
    name: "Florida eastbound: Colorado Blvd to Holly",
    segmentId: 8879841,
    rank: 1,
    line: "uxfqFdeo_SE_B@sACcA@s@Es@BmKAkN@kACaI?aTB}AEe\\EmE?m@",
  },
  {
    athleteId: 1075670,
    date: "2015-11-22T21:57:14Z",
    id: 31047219057,
    name: "Jetta",
    segmentId: 5495512,
    rank: 1,
    line:
      "wogqEftzxU@XH^^h@h@f@Tz@@LEb@Qx@c@v@EVAXFdA@j@If@Wn@Md@GfAFPLLLX@LC^QZIb@An@CVMRM?c@TONGP@^RbA@VGTMVoAfBs@L]@o@@a@HKHEPJd@?\\Rz@AXGZQ^MHOd@QRQXq@xAy@fAMXKVKp@Df@BFJAfB]h@UVCfBEr@Et@B^CXBt@PXLj@j@PXJ\\\\b@Jh@MTIb@?JFDHCEGGAECEM@QAKH_@I}@Qm@MOw@o@c@OH@a@Ai@IYC_@BQCgB?k@Di@VYFoB^IC]UEKx@}Ar@}AVg@x@eAh@y@BKDS?s@Gg@U_A@UBIDGJCFGPAHGn@?^GTGr@a@\\]Zi@Ng@BSAKYg@EOAOFa@Xi@LIl@KJGFM@O?_@@_@Ja@P[BQCc@_@oAASd@iAHa@?{@Ii@Co@BUFS^m@Rm@F[@YAWOi@EIGCOW]]]w@AW",
  },
  {
    athleteId: 1075670,
    date: "2019-09-07T15:46:02Z",
    id: 67255052493,
    name: "2015 Mammoth Gran Fondo 2nd to 3rd Rest Stop",
    segmentId: 10460184,
    rank: 1,
    line:
      "mqgfF`yntUy@qBcBcDaAwB_AkCuA{EeDmMk@eCwCyP]yBGq@CkA@s@Fs@PkAb@}Aj@wAn@mApAwBfAaBh@}@d@eAXqALw@F{@?}AM_BS{@[{@q@mAkC_Dc@m@_C_Ec@c@SMk@UUEo@CcBBcCCu@BYBq@NaG~AmEfAq@Js@@q@GWIUMi@g@_@s@M]Ga@Ea@?a@FcAV_AN[h@o@n@c@dBu@|C_BjAy@TUj@o@`@}@r@kC^eAd@_AzDsGv@}Ap@aBxAeEnAaD~A}DrAqCdCmElGkK~@qA|CcEvDeFbAcBp@wAxAwDhIyUn@yBRqAHy@D}@PgNAuFqFexAS}Cc@_F_BgOqEcm@KoBmDod@SkBeCaQY}CMuCAiCHuEJgBPiBjB{LhAwIn@wCXaB~@oHJwA\\}FDiBAeBGyBKaCQkBwA}KsAgLi@}BgPm`@kO{Y{FaMuE_LcDuH_C}FmDaJqA_DcAmBwMkS}AmCa@cAUs@iBcHaAmEcA_EyKaa@iC_JsD_NoDmNc@oAk@kAyAuBa@y@eBsFa@cAc@}@i@w@{AgBsAsBW[wC{CaDmEg@_AeAiC}@aBcA{AyBuCyAgCcCwCW_@sAyCoBcGi@uAgEuHaAoBOg@MsADi@Le@Pe@rBmExDuIdCgGnAqC|CsH~HsSfAkCdH{Q~@}BxKqYlAwC`GsO|BmGrHqRpb@ijAxGaR~A}Dnb@mjAlKaYxQ{f@vUyn@h@gA~@{AdFsHjKgOxNoTnGaJbNkSnGiJbCgEzBkEtCmFxAwCdAiB`DcGtAcCf@m@p@i@b@UhHsCjBo@|Aq@fBq@rKqEf@WnBs@dJuDvPaH~@c@nDyArTyIpMmFbLoE|XiLbn@uV|UyJ~w@y[rGoCpT{IzIuDdE_BzOsGdGaCdl@{UjVuJzEqBpSgI|BaA~TcJ~EwBxGiCVMRg@NIV_@Zk@Na@",
  },
  {
    athleteId: 1075670,
    date: "2020-04-05T16:51:59Z",
    id: "2680804834388386300",
    name: "Los Flores>Piuma>Stunt>Tuna Loop",
    segmentId: 17292095,
    rank: 1,
    line:
      "_jwnEp_yrUGv@eA`IQdBCfBJlEOhEAp@BhAHhAV|A`@pBNrBf@nV?fDIbHDtANvATtAjDdNRf@`@x@|AvBd@t@^v@Zx@R|@VdBHhB?~@E~@I~@_@~BKtAEzA?dDErBoB~^gAnQI|AAdAFzDJhC^~Bt@hCLj@T|AP~ADn@Bp@?dAGtCI~Aa@xGErA@xAJpBx@jMJz@`@`CHt@DfAAZQPeAn@kDdD_@X]V_@Nk@LU@c@AaBS_AUUAa@DeAZW@KAWQi@cASW_@WWCW@UJSNs@t@e@Z_@NS@kA[a@EY?e@F[JWPc@t@{@jB[b@WRg@PeDt@q@Pc@Tq@f@OHSB_@A}Ba@{BUaCYsBc@QGm@]]IM@MDYTg@h@ULYHi@FgBAyAFoAC_@Ho@\\Q@UIMSAWLw@AWGYSYOEMAc@Pa@b@ITUrA_@xA]h@KJq@lBQNO?MGOS]W_@QSCeAJUEMGWWiAsBY]_@Uq@KMGS{@Yc@uAo@UASFQPKTQt@EHMHk@P_@RO?MCiAu@OGSAIBc@`@w@\\e@No@DSFOHe@n@SJO?q@OU?UDk@RQ@O?i@M[Cw@JU@e@OSAOBGD[p@KHG@GCIQe@yAUKM?QHOLu@dAWXSJkA`@k@X[ZS\\WZ[RUDg@EQGQMU_@GIKCkAT_AEm@B}@^_@Di@BQDEDGN?P\\dB@j@Ct@TzANbBEbAId@m@hBc@bAW`@Ur@]|@GX@PNLJ@J?NIP[Vq@fAaBz@aBd@k@ROv@YTAJ@HDlAhAHPDXQtEYlC?VHf@PP^FV@pBOt@CJCPDXPP\\FVf@jDJb@Zf@jCdDJZCTq@jBU\\{E|CcDnBOFqBvAUVc@t@y@`AQd@_@pAKPOLoB`@W?OEQI_@[k@Yi@Ey@Bq@JgAZm@FcATuB\\YJMHe@h@]p@gAvEWx@g@~Ba@rAm@r@y@j@u@x@QVMZGVAXDb@H^n@dANt@@fB]tAE\\A^D|@J\\R^b@j@TPRHbALRLRP\\PdAXZVX^RLTD^ATCh@QZAPHHHPb@NnBXfAHb@FvACd@MVONKF{@V_@RYROTc@fAe@bBM\\g@~BCTAp@Dt@Px@x@~BJl@@t@EZYpAAZ@ZRv@rBzE^r@RTl@\\XFVBlAIVDNNDT?XGX[bAMhAAXBVJVRJV@~AM`DOj@@VFj@VRLPRzApC\\t@JZJ~@b@jHHlCA`@I\\Yr@I\\A^N|A@`@A`AIdBKbAU`A]|@Q\\_AnAM^K`@y@|EKb@i@zAG^GbAEfBG`@K\\SZWR[L]B_@C]Kw@c@]K_@C_@B]H[LWTMXI^?`@B`@N`A@`@C`@WzAE|CB|APz@xA`EJ\\D`@?^E`@_@fCS`AM^S\\SX}AbBM\\G\\A~AE^MXw@bAq@nASVk@j@SXOZI^A`@FdBC^IZQTULWFYCw@KW@SJQROVWz@QXWRs@`@WPQVMZW|@k@fC]`AaA|Ba@l@SLSFSCOMIS?WDULSPKf@MRMNSVo@HYNy@B[?{@E]K[]u@E]EcBB_@D]JSLKPA^FP?PENKJQFU?oAD[HWNQPKRGd@GPG^[JQ^{BLiBJu@Po@Ze@\\_@JQFU@WAYKs@Uq@OUQSyA{@OSEW@W`@eAPo@BWCYGUi@}@_@kAKUQSUQWIo@KSKMSGY@YDYnAqF\\mAB[A[G[g@sA]eCS{@KUQMSASFMNER^zAHp@B~BAXMl@Wh@u@jAaAfBORe@`@g@XQRg@hBgA`CIZCZRtAAZ_@rBA\\@\\Hv@?ZGTOJS?QIKSCWDUp@mCBY?[EYYo@Qw@C[HyAC]IY[o@KYKqAIQMKQAQDMLGP@j@JbAGp@Up@kAlC[hAQjAk@~FKf@KPo@h@e@XUFWDW?qAAg@CQ@}@RICIGg@o@Wa@K]Ee@@g@XgB@WCm@EUKSW_@m@g@aAk@uB_Au@i@UWQ]k@kBUe@a@a@MIe@QMQO_@SqAWs@[m@g@q@o@s@e@gAS}@[_C_@qBWg@][[O[ISAy@@UA[Me@a@YQ[Gu@COE[Sw@gAYWk@Us@O_@OeB}AMG]Mq@GOBwCAa@BaAPo@FiAHa@AQGOK]_@QMQGg@GkC?[Ks@k@OGa@I{AIo@Is@Qi@UQMSSc@o@SSeAe@eAo@m@Y]EiABUAsAS]KOIs@aAQe@?UR{@BYAa@Ea@Om@{@iBc@sCMg@u@oAcAoAs@u@wCqCQ[e@_Gk@}EiA{Mw@wHcCyXc@sES{AUu@[q@a@i@[[[Wi@Y{@Wq@IIECK@KNk@nA_DJe@Dc@@q@AiAc@wM@y@Hq@Vo@V[j@_@lAi@lCgAvAWjBUb@Kd@Sh@e@nB_Cb@[f@Sf@O`@Gx@?h@@p@Pt@^\\LVFZB^AXGVMXUTYLYN{@Be@?c@Gc@I[e@oAMo@Gs@MgC?oAHiA^qDLs@L]V_@TQf@OVA\\FbBZXLRPFLJ^?XMn@aBvDMb@ET?VBVFTVZdAh@JHLPJ\\RhAv@bBFZJrAH`@Zn@Zb@RP\\JXBz@@`@HXVh@hAX^\\RfAXVLXZNd@Br@E~BEj@Mp@s@pBQv@E`@?b@JdBAf@Kj@c@`BGd@A^Bh@Jr@Nf@Nf@NZNRh@n@vCrCXP`@PvAf@~@\\JHRTLVDX?TYnCEl@@xCDz@Pv@b@x@fEzE\\P^@\\GTOVe@BM?_@Gm@e@aBCWBg@JcAZuB`@eD\\qBZ}BLaAFaA?aBk@mG?]B]P_@Z[XM`Bi@ROV]JYHm@?eEIiCMgAYuAK}@?{@L{@Rg@h@s@j@c@|B}A\\_@Zq@Lc@Jm@JkAFYTc@TUh@O|@MtAMf@?RFXPjAfA\\Tb@Lf@@\\GZMNMNOLSHWJ{@?a@GaA}@oJa@kDg@kCKo@?SF[SmAHiBMgBAaANqCHqDRuD?a@K_@O]{DgIW]YY{@i@KMGSIe@q@}EI]Yc@kAu@YWISCI@a@Nk@xAeDBSJyAFYRi@t@oAF[Fu@LYLOPGPApBHNCNMLWD]@c@EmA?UFKHIRCJDZTp@v@RHJBJCd@S\\ENBLD`A~@\\PNBPAt@OP?v@TR?PAPK~@{@vA}@Xc@j@oBd@{@FUJiAJo@xCuGTq@Ns@NoAJWLQb@[LQBq@AY]gC?[DYJWPOTIfAOVIROLUFY?YEYIWQSy@m@OSKWEs@B[Ts@Zo@l@aALUDYDmBFYJWNSTKTEV@TFh@VVBTCRKb@a@JUHYB[AYC[GWc@{@}@iAIOCSBe@Ts@Fe@CWe@{AOqA?[D[b@eABW?WGq@?WDWLQp@s@LSDYBuAD}@Z}CD[HWNSz@s@RMRCTFtAp@NPHT?XEXIXeAxCCX@XHRNLPBPC`@[RGR?PJ\\`@PHRAPIJSTm@JUPQ~@m@x@y@TITA|@VT?VGdAa@`Be@j@[NSLUZgANgAD_BCUGWQk@KiAEUc@w@Qi@CY?YPkANiBDS^k@HGJAHFDLA\\Mp@]h@Ul@C`@B`@j@lAX`@HZB`@DNRX^TJNFRJz@f@d@FRDh@HPNJd@JPLJTFVAXWz@?RDPX`@FR?TGTKNcA^WZGPATBTJPLPd@XTHTBj@Ah@BRATGzAu@l@Uj@O~@MjAc@P?NHb@n@RJRFdA@TBRHPJXXh@z@RJTFJ?^QXG\\Dj@VND`@CfAYb@Eb@D`ATP@PCPGNMvB}BXk@FWBWAWEU_@uACUCs@DmACYIWi@_AWq@Ou@Ky@KgDWcB?YDYHYFs@_@_Fa@iC@[ReAAUKm@AULwAI_A@UTy@`@sCXkADY@YCYQeA@WFULS`AeAFS@QCQKa@@QFMJKPClA?RERIPOHWLsA?uCA]Gy@SgA@SHOr@_@r@m@RITAj@BRCPK^e@v@m@^e@NKN?LHHPDTDdBHv@FVJRJLNDJAFKEaANgADmBPs@LQRKbAGl@IRKd@_@f@e@\\o@FWH_AFOLIPCz@?REPM`@c@HSTy@JKNC`@DNALI`AmBNUp@y@Vg@LONGNAPFz@^x@l@JAFIBOCcB@OFKLEN?v@Zf@NR@PCf@QRCT@x@VNALIHSBU@eADSHMv@e@PQj@y@r@mAb@a@`A{@~BgBf@Oz@Ed@IPGNKVe@Rq@`@yAX{AJy@Bq@?YQcAAW@WDULSNOv@i@NQHSDWDqAZqA@QCOGMKGMBIL[t@yApBMFM@KEIKAO^}Ad@mDTe@^_@f@[h@QRCPBf@R~A|@~@T~@^TN\\h@JVZpAJVLNN@NEr@c@~@[n@Kl@AVE`BWn@Qh@[PSVg@NOPGR?P@lB^j@V`Ax@LD",
  },
  {
    athleteId: 1075670,
    date: "2016-10-07T12:15:56Z",
    id: 18071782865,
    name: "Humboldt Hillclimb",
    segmentId: 9360127,
    rank: 1,
    line: "g{lqFbzt_SO?[Ey]B?GBDEAgAHKAQEeBF[EkA?KAk@FYFg@?KKKLIM[?IHKIm@?IDIEi@?YEa@A",
  },
  {
    athleteId: 1075670,
    date: "2018-08-25T14:37:11Z",
    id: 45103356472,
    name: "Westminster Station to 8700",
    segmentId: 13066114,
    rank: 1,
    line:
      "sx`rF|q``Sr@h@XLFN@HKNYr@K\\ERFb@Ip@GdAAbDBfBCLWl@y@~@Q`@OdAClBCFGBOI_@GcAEiB?_@DcACi@CoBAeAEuBEw@DgFCkDHgD?KAQK[HS@uCCoABUAiD@{@Ge@@GCyADmAAYDOEqA?WGu@Gk@HkAE{AHyA@mDCwABsAAeBBi@EMBUPW^e@`@[p@a@l@_@hAmBhEa@bA_AjB_BvCiA`Bc@f@Wb@k@p@Wb@Sf@K|@CxABx@Aj@CJIFc@F_@TO@Ih@AtAG`@O\\gCtBo@`@MDsB?e@BaBCi@H_@^_@`@EJALDLXHFH@NALGHkDfDg@h@qAnAW\\IPyBtBkBpBg@^aAfAm@f@]^ELsAnAY`@e@|@UZIj@KTcD~Cm@`@o@n@{@~@i@z@G@KGQi@KMECQBMJQZA\\CHDCCMDEFLF^",
  },
  {
    athleteId: 1075670,
    date: "2017-06-26T13:52:49Z",
    id: 26012816959,
    name: "OLD VERSION - TAIL CREST CHUTE",
    segmentId: 15194102,
    rank: 1,
    line:
      "}bd~Enz|pUGJDLBXJd@r@rBfArDA~ADj@Ch@Fj@EtABj@Hb@EvALlAIvA?h@Nb@\\z@HdAHZFf@Dd@Ah@Ih@?zBD^n@h@Bb@h@RVOt@Th@jAr@bAf@pANV^f@P\\NG",
  },
  {
    athleteId: 1075670,
    date: "2017-07-26T17:17:53Z",
    id: 27154182697,
    name: "Bear Creek Tri Course",
    segmentId: 10095222,
    rank: 1,
    line:
      "yhaqFnxv`SlAq@nP}GREV?RBVHj@ZRNRVLVJ\\F\\B^A|@CxB?|BJtAPpANp@~@fC|ErKJh@@f@Cz@@TJd@T^\\T`@DPCNENMnA}AHAFBDH@JALYr@[bBKdAChA?d@DjAjApM^zENzB^~OHxFBpGPtC|@fJZzDPpCFnBHhDB|DPhVFbLFnBHRXV~A|@v@^XTTZL^R`BPp@TXXJ\\?NGJKP[h@_Bh@uAR]FGRKTCTBTH|BjATHXFZ@Z?\\Gh@Sh@_@`@k@Zy@fBsGf@{A\\}AHo@Bs@?eBEo@Mm@Wg@MOOOa@YgB}@a@W]]w@gA_@_@a@Ys@a@o@o@[g@kC}Fm@aAa@e@[i@Wm@Ms@Aw@PcD@w@?qBFgDL{Bf@{BHu@Au@Ms@Qq@Ks@Ds@LiADkAJk@t@{@Pe@Fi@DuAHg@T_@LIREdACbAO`@C`A@hHLbCBRCDG@ME[y@eCsAkEaKk[Se@q@gAWi@uAyDGKCACBTf@H\\x@nBzArC`@dAtEjOz@dChAvDt@vBVbAp@tBVn@FTARMFyBGqHGgBFgBRi@BSF]\\Qj@En@AdACTQf@g@h@MPMh@IzAOtA@h@Hh@^fADd@@d@Gd@g@nBKp@OjEA|ABjBQnDAfAHp@Tl@`@t@n@x@Zf@|B|El@jAPT\\ZbAj@TP^`@|@jATTn@b@hB~@n@h@Xl@Lv@@d@AfACfAE`@K^wDbMSf@[`@i@`@UHs@JY?s@KsCuA[I]?]LYZs@lBc@tAS^OHO@OCQIMMMUa@iCIY]i@e@_@w@_@kAu@WUGOAWEaAYug@GsDGuBSqD[wD_AoJUwCE_BC{FEcCMgEM{H?{@C}@c@qFyA{OEeA?iAJ{ALaARy@La@F]EKGIIAIBiArAYRUDUA]IKKQWKa@CWDqAC]E]K[wFyLSg@U_ASeAMaBCeBDoDEmAGc@M_@We@YYk@Wi@O]?_@FaBv@mLzEeAf@e@V",
  },
  {
    athleteId: 1075670,
    date: "2019-10-05T18:59:42Z",
    id: 69005926897,
    name: "CX Sprint",
    segmentId: 21982617,
    rank: 1,
    line: "kdcpEvpesU?IMk@iA{CwCcEoC}C_@i@Yi@{@w@e@o@sBsD",
  },
  {
    athleteId: 1075670,
    date: "2017-11-22T17:07:36Z",
    id: 31797289610,
    name: "Jasmine Sepulveda",
    segmentId: 12422588,
    rank: 1,
    line: "cxsnEnotqUpBlEpAjCfF|K~AdD|@rBnHnOdIlQ`IjPt@fB",
  },
  {
    athleteId: 1075670,
    date: "2019-10-08T17:18:57Z",
    id: 69184589769,
    name: "RHCP",
    segmentId: 6988367,
    rank: 1,
    line: "ep`qEdipyUgAvAoArB]v@iBhC",
  },
  {
    athleteId: 1075670,
    date: "2016-06-22T19:32:48Z",
    id: 31047707425,
    name: "Mira Vista Ave Climb",
    segmentId: 1278447,
    rank: 1,
    line:
      "kjcqE|dryUyHjLc@l@_BhC}DbGiA~AwEnH{B`Di@^YOoCwCMi@BqE?m@ISUEg@j@wAnBQ@YOSUKYEa@BeDPeABg@Ma@q@_@WQB_@VeA@k@Ck@g@iD{@cHEm@@uAGuAc@qGSsA",
  },
  {
    athleteId: 1075670,
    date: "2019-12-02T22:19:18Z",
    id: 72158946468,
    name: "College Blvd Descent to Jefferson",
    segmentId: 3350404,
    rank: 1,
    line: "myqnExjqqUYT_AlAkApAONgAn@]^Yd@S`@]xA",
  },
  {
    athleteId: 1075670,
    date: "2017-09-01T01:28:21Z",
    id: 28636652139,
    name: "Louisiana westbound: Franklin to Downing",
    segmentId: 9862067,
    rank: 1,
    line: "kpgqFxvt_SAb@BpBAjC@`HCxG",
  },
  {
    athleteId: 1075670,
    date: "2019-10-24T13:46:56Z",
    id: 70059937193,
    name: "Las Flores Canyon Rd Climb",
    segmentId: 1453554,
    rank: 1,
    line:
      "or{nExvbsUMn@WEYNK?K?UM[FQHYZq@f@g@t@y@`B]DWLIHkApCB{@M[OKm@U_@@MFWRIDIACEAa@GSIIMCSBo@h@]JK?KI?IGGG?MFMD",
  },
  {
    athleteId: 1075670,
    date: "2018-12-27T14:31:57Z",
    id: 51397343041,
    name: "BikePath Ballona Creek",
    segmentId: 11002281,
    rank: 1,
    line:
      "klnnEjvwqUVLnMvJv@GBLHNIFb@VJPLZxK`InQ`NJ?VW`CoAxAiA|HuFjCsBRCTHt@dBpBjC\\VHp@JZJr@f@lAfBh@xFpIbAjBPRL^h@r@NXBTh@bA|@xAl@hAf@r@h@bATTlAzBXp@FVj@fAbC`EFd@bBhDn@rBPPd@nAZj@FP`@|@n@|@f@`Al@|APXJVj@fA|@vBx@xAhCvFr@fATp@nBrEnC~Fb@lAhAxB|CzGp@jBz@dBbAzB~@|Ah@fA~@|Aj@lAhAbBh@nARVzAtCn@fBf@lAT\\h@pA`AjBn@zAx@rBd@vARZTRLT",
  },
  {
    athleteId: 1075670,
    date: "2017-09-06T15:46:08Z",
    id: 28864068259,
    name: "RMRC Hill",
    segmentId: 1009913,
    rank: 1,
    line:
      "cqsqFn}y`SBv@J~EA`@K\\KJYPUXEPATHZl@l@DL@LANGPIHKDm@AMBMHINEP?RDLHJb@ZNVJn@@p@A`@Gb@M\\Yh@K`@Ed@?lAQhBGrA",
  },
  {
    athleteId: 1075670,
    date: "2017-02-08T19:15:07Z",
    id: 20944280402,
    name: "Florida eastbound: Colorado Blvd to Holly",
    segmentId: 8879841,
    rank: 1,
    line: "uxfqFdeo_SE_B@sACcA@s@Es@BmKAkN@kACaI?aTB}AEe\\EmE?m@",
  },
  {
    athleteId: 1075670,
    date: "2017-09-01T01:13:59Z",
    id: 28636652098,
    name: "Downing northbound: Louisiana to Virginia (Wash Park west side)",
    segmentId: 12412828,
    rank: 1,
    line: "mqgqFvru_SqD@eECgJ@aECoABoFCe@@oDAsABi@C}BCgBBgBAkM@qBC_BBoAC}AB",
  },
  {
    athleteId: 1075670,
    date: "2019-09-07T15:46:05Z",
    id: 67255052473,
    name: "Fall Century (Fondo) 2nd to 3rd Rest Stop (accurate stop)",
    segmentId: 16001376,
    rank: 1,
    line:
      "grgfFfwntUmCmFmAwCgAmD_C{IuAsF}@mEuBqLe@_DQmBAaAD_AJ}@^yAn@cBx@cB`DiFl@gARi@VaAPiADs@?kBEu@Mw@Qu@Yw@o@iAeCyCc@m@{BwDQSc@c@i@WYGo@EuF?y@D{@NoCv@qHjB}@N}@@]C_@G]Q[UW[Q_@Oc@Ic@Ce@Ag@Be@Fc@Ja@N]d@o@l@c@zDmBvAy@|AmA^a@f@cAp@cCr@gBfAoB`C{DdAwBxAwDt@wBhDkI~@sBbAkB`DmFbDyFlKoN~@yAr@qAVi@~@wBfDmJrEqMXeAHc@RmAHcAH_CN{KAqF_C{l@{Amb@WoG[eE_@kE}@eI_@iEgI}gAeA}LUwBiBaMYaCUwCIeCCaBDcDTkEN{ANmANk@tA_Jt@aGVwAViAf@wCx@kHh@iIBgBCqCS{EMuAcBsMcAaJWsAa@mAgImSu@aB_BaE{@kBgOyY}BcFeCmFeF_MqBqEiEsKcDqIu@}Am@kA_MkRwAaCm@gAWq@Ww@qAaFuDmOcAgDy@_DaMkd@qAwEi@_B}AkGoBkH}@kBmAiBc@q@i@wAyAwEo@qAw@gAmAuAgBqCcDmDiCkDc@w@iAoCm@mAgBgCgB_CaBuCsBgCu@iA{AmDoAaE]_AeAwBoBgDiByDSw@E]@y@DYPs@Tk@zCeHv@aBdAkC|@oBbG}Nn@cBxBoFpEyLl@{A|EkMbDiIbBsE`@_A\\_A`FqMZaArGkPlHqRr@oBZs@lAmDzC}H|CsI^{@hBgFhFcNxDsKpAcDnTsl@dAmChKiYfLyZl@gBd@gAtGsQjIwTvDkKdBsEtGoQ`DoIvEkMd@kAnBuFlA_D\\q@tAuBR_@xDoF`BkCnKqOhAgB\\c@rB}Cr@_AdDyEdHoK~EcHzHaLp@iAl@y@bC{Df@_AN_@`@o@hLiTf@cApDwGv@eAn@g@j@[zB}@f@WzAi@n@]`Bk@pAm@~EqB~Ak@xDaBf@QlFyB`I_DvEqBvHyClN}F`Bw@lDwAf@Ob@Un@SjH}ClAc@nAk@jDsAlAi@bDsA`HoCv@]hBs@zQuHzGkCrIoDhBq@tF_CfMcFbLwExIiDrFaCpV{JbAe@jEgBtCeArAm@rCeAlNyF`@WlA_@fJyDpMgFzYwLdVqJvFaClAe@NIdEaBz@a@bA]hGgChCcAdOkGhJoDrFaChBo@`FwBxD}A`C{@vQqHr@a@p@U",
  },
  {
    athleteId: 1075670,
    date: "2018-07-13T14:57:13Z",
    id: 42602125939,
    name: "Rua marcos portugal climb ",
    segmentId: 9440218,
    rank: 1,
    line: "avhkF`pzv@GBK?c@PYTm@\\ONE?w@q@",
  },
  {
    athleteId: 1075670,
    date: "2016-11-25T17:57:16Z",
    id: 31047929743,
    name: "Santa Monica (down)",
    segmentId: 4323191,
    rank: 1,
    line:
      "ck`qExmpxUvAt@PDRANGFYJw@HWLQZKP?RDjEzAnCfATBf@GLIXa@^Qd@DbAVdA\\VDV@`AAfCUfAMl@Aj@JrAf@tGhD",
  },
  {
    athleteId: 1075670,
    date: "2017-09-06T17:42:54Z",
    id: 28864060138,
    name: "Gulch Trail Sprint",
    segmentId: 11523280,
    rank: 1,
    line: "qwoqF~a``So@WAo@CWIUOOQIe@QQKOOYg@u@kBEQGI]IQKGKIsD?gBOoBHsC",
  },
  {
    athleteId: 1075670,
    date: "2013-09-05T01:45:59Z",
    id: 1628078708,
    name: "Santa Monica to State",
    segmentId: 4053574,
    rank: 1,
    line:
      "{t~pE|vpxUZp@VlC@p@AVObBwCzWiB|Om@xEC~AGdRAvAIjBMfBY~BYbBk@tBq@lBu@xAeAhBuChE[^cAfAgLjLmAzAw@bBqE~KkAlC}@zAu@`AaGdHaBdBUZy@`Bq@bBa@vAOv@QlB_AbQc@jKEpA?nABxBDhAj@`IGV@RBRLPRfD?bAQ~DAd@Dh@f@fHn@~Gt@nDLlA@nAO|EYrCa@vBkAnFm@zBoBlFUx@QhAGjA?h@p@lIDtBCtBIlBQhBWdBWrAi@lBeEhMc@dCwBtQYdBm@hCcFvPy@|CUfBIzASR?p@PR@bAJbBXzBDv@?d@Cv@YrCp@IV\\PdA^`DXjBKJFdCApBKtCKvAcB~NUpCA^OpAKLK\\A`@IdBa@nDIrAk@fARp@~AfJJz@PnBjAhR\\`LBjCCjCWlKS|COvAa@`C{@jDaCdIUn@{@jBIVEh@A`@@tGVfITpE\\zB@^FZHL`BxJTdB\\~C@HNRDVBn@DTGhAHxAXlAVp@Np@XhBDxA?v@GxBCPA~@E`@?zAEt@BjBWtBEh@S|@YzBEbB@XCp@ClEDh@AfAK`BE^U~@mBpFMNYJi@GMLEH?TVr@HJ?NEZ_@bACPG\\@ZRjARn@\\n@v@jBrAlCNNd@^z@d@tA`Al@p@`@dABRVr@Ll@ThCDfA@bAHrBAn@FzAAl@HnARl@LTX^|@v@bBx@b@P\\Fp@`@Zj@JVHb@HlBf@xBRtCZfBVbDNz@@j@C\\Dx@En@K~C@fABx@N|Ar@jGNjALp@?VHZb@jD`@jETnBj@vFN|@Fx@RbALpAPx@FpANz@B~@ZhDBz@Hh@Ff@@P?ZJf@@PETHh@A|A?h@Hf@ATLbBD|@L~@BrAFn@@d@Hz@B~@XnBHxAPxADh@TtAh@dB\\x@Nf@\\VnIdJ",
  },
  {
    athleteId: 1075670,
    date: "2018-03-31T16:46:57Z",
    id: 36951953935,
    name: "Louisville Crit Finish",
    segmentId: 6099476,
    rank: 1,
    line: "_v|rFnl{`S_@pBKRGTMfBMnDMnAI`@Mb@_@t@e@v@QPWPYNYJq@L{@B_AMWGgAs@USm@{@Sc@",
  },
  {
    athleteId: 1075670,
    date: "2019-03-27T13:23:44Z",
    id: 56693006408,
    name: "upupupup",
    segmentId: 6276512,
    rank: 1,
    line: "sxynEbmbrU^|DXdBh@hFLhALn@FjAFRHl@Bt@RbB",
  },
  {
    athleteId: 1075670,
    date: "2016-03-19T21:44:43Z",
    id: 31047352202,
    name: "Alamar to Constance",
    segmentId: 10604473,
    rank: 1,
  },
  {
    athleteId: 1075670,
    date: "2016-08-31T19:36:41Z",
    id: 17068248740,
    name: "First Bank Strava-Wank (N)",
    segmentId: 10539618,
    rank: 1,
    line: "ahprF`yj`Su@h@yApAmKvGgC`ByAnAsCvByAz@oFjCkAn@sInFgGpD",
  },
  {
    athleteId: 1075670,
    date: "2019-01-03T00:20:30Z",
    id: 51741168724,
    name: "Counter Clockwise College",
    segmentId: 16616440,
    rank: 1,
    line:
      "ecqnEpiqqUQ\\aAtAS`@Ut@Ib@BPFLJJ~@b@tAl@|DpAtBx@pFhBjAf@`C|@jA\\fAb@hAZp@Z^T^JLAJIRm@Z}ALw@NwB\\iHF_CFiAF{CGaEC_@KSUIq@C_CDuBHuBDkHZiDFq@Ho@RWL_Av@e@j@q@jAc@j@",
  },
  {
    athleteId: 1075670,
    date: "2016-07-21T18:36:46Z",
    id: 15873474669,
    name: "little sprit",
    segmentId: 5977551,
    rank: 1,
    line: "o_bqEzhiyUi@u@mA}B_@{@YoA[u@A}@Py@^o@Xm@Bm@A[DWC@",
  },
  {
    athleteId: 1075670,
    date: "2016-11-10T21:12:38Z",
    id: 18887047499,
    name: "Beech Street Jam",
    segmentId: 10372654,
    rank: 1,
    line: "qosqFn_w`S|BtA`DrBzC|BfEtC~BdB~HpFbExC",
  },
  {
    athleteId: 1075670,
    date: "2015-12-09T18:09:35Z",
    id: 31047276755,
    name: "Across the park sprint: Northbound",
    segmentId: 10776008,
    rank: 1,
  },
  {
    athleteId: 1075670,
    date: "2020-04-04T22:11:10Z",
    id: "2680804834036323000",
    name: "Home to JJ",
    segmentId: 1144378,
    rank: 1,
    line:
      "egunE~h|qU{@r@g@h@GL{@p@@CJ?TE`Fa@qBzAoCdB{@l@WTo@p@aBbAm@j@eBdAUH@C]RqBpAgAx@yBhBuApAgIpGaA~@k@b@_@b@kAdAyAjAwA~@gAbA{DxCURa@l@sEpDqBhBuAhAcAt@eDzCy@l@[Zq@d@a@R}@l@kAbAuAnAeAr@[Zk@d@k@p@g@\\gAbAo@h@e@Xu@t@oAdAkAx@cA|@gAz@Wb@QNOTENGLu@x@o@^i@`@aDtAOJ_@h@]TSV_@t@KLk@f@q@~@gAhAuCxDe@b@U\\i@l@o@z@}@bAu@`AED?KMNe@l@OTAF@PPxAFPVnBp@vFZdDFX?`@F~@ER",
  },
  {
    athleteId: 1075670,
    date: "2017-05-17T17:13:21Z",
    id: 24324886200,
    name: "A little climb for the little men",
    segmentId: 14132849,
    rank: 1,
    line: "gvpqF`fl~R?kkA",
  },
  {
    athleteId: 1075670,
    date: "2017-09-07T17:45:41Z",
    id: 28905063905,
    name: "DC Final 500 Meters",
    segmentId: 12824593,
    rank: 1,
    line: "iumpFr~caS{@h@u@Zy@NwARy@PaAZoDrAeARg@Nu@ZaD`Bm@P",
  },
  {
    athleteId: 1075670,
    date: "2017-09-06T15:33:39Z",
    id: 28864068095,
    name: "Beech Street Jam",
    segmentId: 10372654,
    rank: 1,
    line: "qosqFn_w`S|BtA`DrBzC|BfEtC~BdB~HpFbExC",
  },
  {
    athleteId: 1075670,
    date: "2018-04-07T18:19:27Z",
    id: 37294396364,
    name: "Mountain Loop Rd (StopSign to StopSign)",
    segmentId: 759956,
    rank: 1,
    line:
      "seqjFzy`zSJD\\`Bb@j@RLrAb@lCz@dA~@x@|Av@`BTtBE~Ai@vBcBrDyEhJe@bA_@tBOjD@rAVbDh@jCZ~@PdAApBI`@kD|M_@lBCXB`B`A~E@RAjAq@hCwFtPkAvB{BbBu@TeC\\cBl@WNeAbAkBhCS^kBrFgArD_@fAw@fBgB|C}FjJeCxEa@~@sCnIsAjEgDzJgAvCw@lAUTo@h@kB~@wJzDqDpBYZwAjCoBrFcBpCoFnHsC`EwDdFgBvCqB|D}AvCyS~b@iMnWsOv[kXpj@yRha@w@xAsBlBgBj@wGh@yAb@mA|@aArAwD|GuRv^_BtDy@`CiA`EmB~KmAhF{@jDgAzCg@lAmBnDiE`HiLxReX|c@oBlDeAlCm@dC[tCI~A_@hUYxUQlJ[nGc@xDs@tDa@dBuDlMk@`Bo@zAuAjCoWt_@sCvDgBrAsAf@aBTQ?qACsAWsAa@uCaAu@_@k@a@kAcAeFqFmBgBmBaCcCkDkAu@}@PmBpAaCZeB@aBd@gEtC{@\\_Dt@aCNiKF}BNy@TeBjAsAfBiBbDc@p@{A|@[FwDPiCTiCp@a@N_CjA_IdF",
  },
  {
    athleteId: 1075670,
    date: "2016-06-29T16:15:35Z",
    id: 31047744256,
    name: "Gibraltar, Sprint to Concrete Barriers",
    segmentId: 5706637,
    rank: 1,
    line: "eajqEv_nyUA[HQHGhAWxB?VGROHOBMBaBHUPUl@i@vCu@LIJMDO@SCSU_@",
  },
  {
    athleteId: 1075670,
    date: "2019-04-10T14:52:28Z",
    id: 57575471942,
    name: "Single Lane Sprint - Southbound",
    segmentId: 19965824,
    rank: 1,
    line: "srsnEte{qUlGwE~@u@f@g@pAoBJUZmALs@PmAT_DHs@TiAXgAJUXg@dAwAh@g@t@k@",
  },
  {
    athleteId: 1075670,
    date: "2016-07-14T15:00:29Z",
    id: 31047824342,
    name: "Anacapa (Arrellaga to Gutierrez) Sprint",
    segmentId: 751632,
    rank: 1,
    line:
      "{ecqExnsyUVa@|@cAdBaCvI}M~BkDt@}@~@gBx@kAdAmBXa@dAiAjGqJfAiB~@wAx@iAjByCzBaDp@oAtEiH`AkAjAoBhAeBHKLW",
  },
  {
    athleteId: 1075670,
    date: "2016-10-20T16:44:43Z",
    id: 18396229856,
    name: "Col du Plains View",
    segmentId: 2247901,
    rank: 1,
    line: "ubcqFbtbaSq@IMSSo@OqBGWMUOOUIuAUQAMFGLPl@^d@DNH^C^CJe@t@cApBg@xA",
  },
  {
    athleteId: 1075670,
    date: "2013-09-29T14:48:14Z",
    id: 1768552420,
    name: "Sammmy sprint Tri",
    segmentId: 5465804,
    rank: 1,
  },
  {
    athleteId: 1075670,
    date: "2019-10-08T17:18:55Z",
    id: 69184589778,
    name: "Under the bridge sprint",
    segmentId: 6982062,
    rank: 1,
    line: "un`qE|gpyUc@j@g@b@iDrFMRu@lBW\\",
  },
  {
    athleteId: 1075670,
    date: "2019-11-15T15:26:15Z",
    id: 71233690047,
    name: "CollegeChameleon",
    segmentId: 12875898,
    rank: 1,
    line:
      "o|onEherqUi@_AJkAN_APyBNsEFoDAi@HkD@aCE}BEg@UYa@Ig@A_BBqQl@sBJqBf@{AvAoAbB{Af@yA[qABoCd@{BNyBJaALaA\\{@x@aAhAoAlA",
  },
  {
    athleteId: 1075670,
    date: "2016-09-02T17:10:33Z",
    id: 17116020848,
    name: "Mississippi-- I AM TRAFFIC!!",
    segmentId: 8058447,
    rank: 1,
    line: "ughqFxmy_SBjFA|N@`JA|ACJIH",
  },
  {
    athleteId: 1075670,
    date: "2019-04-14T14:56:25Z",
    id: 57883716254,
    name: "Sepulveda/National to Pico/Military",
    segmentId: 1329675,
    rank: 1,
    line:
      "o}tnEvpyqU_@?_@{Ag@aAOc@Cg@o@{B_AmBg@iBGK[?mBbB{AjAqBzAiD`C}AlAeAhAoBhA}AlAs@`@wAjAcAp@w@n@o@^oCtBo@ZgBjAaBrAwF`EQJI@EC",
  },
  {
    athleteId: 1075670,
    date: "2013-09-06T19:44:54Z",
    id: 1637706121,
    name: "Santa Monica (down)",
    segmentId: 4323191,
    rank: 1,
    line:
      "ck`qExmpxUvAt@PDRANGFYJw@HWLQZKP?RDjEzAnCfATBf@GLIXa@^Qd@DbAVdA\\VDV@`AAfCUfAMl@Aj@JrAf@tGhD",
  },
  {
    athleteId: 1075670,
    date: "2016-07-04T18:32:54Z",
    id: 31047783541,
    name: "End of Cuervo",
    segmentId: 4111085,
    rank: 1,
    line: "o~`qEte}yUSm@O[o@q@U]g@yASs@MW?MBGFGHCN@PD\\Xh@r@",
  },
  {
    athleteId: 1075670,
    date: "2016-10-27T20:44:13Z",
    id: 18560807602,
    name: "RMRC Hill",
    segmentId: 1009913,
    rank: 1,
    line:
      "cqsqFn}y`SBv@J~EA`@K\\KJYPUXEPATHZl@l@DL@LANGPIHKDm@AMBMHINEP?RDLHJb@ZNVJn@@p@A`@Gb@M\\Yh@K`@Ed@?lAQhBGrA",
  },
  {
    athleteId: 1075670,
    date: "2019-01-18T20:06:35Z",
    id: 52904137729,
    name: "Esther Way Climb",
    segmentId: 1055283,
    rank: 1,
    line: "wp_iGjpocTQEK@q@EYGk@D]GWC]E]@iECqDO{BGs@GoBF}@GUS?Q",
  },
  {
    athleteId: 1075670,
    date: "2018-07-14T11:27:25Z",
    id: 42646490778,
    name: "Rua marcos portugal climb ",
    segmentId: 9440218,
    rank: 1,
    line: "avhkF`pzv@GBK?c@PYTm@\\ONE?w@q@",
  },
  {
    athleteId: 1075670,
    date: "2019-10-26T20:04:37Z",
    id: 70194728615,
    name: "2017 Casitas CX (Sat preview)",
    segmentId: 16317407,
    rank: 1,
    line:
      "a~~pEr|lwUTyCBqAQ]ElBMb@Ef@CDq@FEE?SACHQHu@HcAD@?BDhAD@FGFODY?c@Lo@@_@EYq@kBi@cAi@qBYm@EAc@NCH@j@HLP?EWL?r@rALb@I`@SHDLh@ALD@JGJ@f@Nh@EHGECG?UI]WOi@MECS[Yq@]c@OGKBCDG^Hl@@x@FLNGB@JR\\GL?RHH`@JXHK?OFOLFRh@Rz@?l@ARKXOPATi@r@GRNEj@EPDZKPBNKAPYjAOHMCMBWTXLGPq@dA@JDDH\\@HG|@U|@DVb@Z^_@@\\XIVSJOHQJo@Za@fA_@VDh@?\\LD@FCDG?IMOE?MJSDo@GiAEcAOSIQM[a@IODKf@Yb@cADQ",
  },
  {
    athleteId: 1075670,
    date: "2016-10-07T12:16:57Z",
    id: 18071782881,
    name: "Hum Bolt Up",
    segmentId: 9517438,
    rank: 1,
    line: "i|mqF`zt_S_CDaAEyA@{@G[@{@C}BFu@Ac@@WAYDq@@]CkAB[CeAAeGJ}@EyBDuAGs@BgCA",
  },
  {
    athleteId: 1075670,
    date: "2016-07-31T21:57:23Z",
    id: 31047911202,
    name: "School House",
    segmentId: 3064833,
    rank: 1,
    line: "smdqEnudyU?|ARr@bA\\`AArB[f@VLd@OpC?~@Ct@MjBCzB`AfDF`BEx@@r@TzABn@A|@WjA@`@CbADhAAnA",
  },
  {
    athleteId: 1075670,
    date: "2016-07-05T15:55:34Z",
    id: 31047793025,
    name: "The Wall",
    segmentId: 6168615,
    rank: 1,
    line: "mc_qEr`dxUPOn@@p@`@Zb@Rd@Nn@X`BFl@DtADZHXZf@n@p@p@`An@p@",
  },
  {
    athleteId: 1075670,
    date: "2017-05-17T17:20:21Z",
    id: 24324886365,
    name: "Colfax (Gunclub to Powhaton)",
    segmentId: 8885686,
    rank: 1,
    line:
      "aipqFr|b~RGIKE{AYa@Ka@Q_@U]Y[][a@Wg@Uk@YiAMq@KqAB_NHcH?qD@ur@BiDJoIDkPM_QFck@A{FB{CDgB\\sGJ}CFSLE?E",
  },
  {
    athleteId: 1075670,
    date: "2019-10-17T19:57:57Z",
    id: 69681822746,
    name: "Sprint to BC",
    segmentId: 3805309,
    rank: 1,
    line: "owlnEb~xqUR_@^[p@a@tAeAf@YzAiAbAo@jA}@x@g@VYXUd@YZ]FM",
  },
  {
    athleteId: 1075670,
    date: "2014-06-03T16:59:13Z",
    id: 3421424171,
    name: "RHCP",
    segmentId: 6988367,
    rank: 1,
    line: "ep`qEdipyUgAvAoArB]v@iBhC",
  },
  {
    athleteId: 1075670,
    date: "2014-06-03T16:59:10Z",
    id: 3421424194,
    name: "Under the bridge sprint",
    segmentId: 6982062,
    rank: 1,
    line: "un`qE|gpyUc@j@g@b@iDrFMRu@lBW\\",
  },
  {
    athleteId: 1075670,
    date: "2019-09-07T16:05:10Z",
    id: 67255052458,
    name: "Barton Flats",
    segmentId: 8339700,
    rank: 1,
    line:
      "snmfFrnosU`HgObEuJtF_NhEgLvRsg@~@}B~Mc^rAcDlCkHlGgPd_@kcAbF}MjBkFdDuItRwh@rHiSzCkInH}RdA{C`AcChQye@nFsNrEkMbH}Qt@yAvI_M`K_OfJiNlGcJtW_`@zCgFnDaHbGyKnBwDnCaFn@w@l@e@r@]pD{ArDwAjJ}D`K_EfEgB`IaDlEkBnDuAnAo@~@[t@_@dA[xJaEt]qNnAk@|Ak@rGoCvD{AVIvAk@fKiEtFyBtJaEpIgDxJaE",
  },
  {
    athleteId: 1075670,
    date: "2017-09-08T14:19:25Z",
    id: 28931733737,
    name: "Louisiana westbound: Franklin to Downing",
    segmentId: 9862067,
    rank: 1,
    line: "kpgqFxvt_SAb@BpBAjC@`HCxG",
  },
  {
    athleteId: 1075670,
    date: "2019-12-02T22:17:56Z",
    id: 72158946447,
    name: "ImA Calledge Stoodent!",
    segmentId: 5057161,
    rank: 1,
    line:
      "y}onEv}pqUcA@eGVwOh@m@LWH_Aj@w@x@yAxBQLSDSAQEa@Qa@Me@CQ?w@LcAVeARq@FaBF}BNuA\\OFYXqA`Bk@r@a@\\y@j@c@b@Yj@a@|A",
  },
  {
    athleteId: 1075670,
    date: "2016-09-01T21:52:20Z",
    id: 17095894060,
    name: "Colorado to Steele",
    segmentId: 11198286,
    rank: 1,
    line: "yyfqF`go_SH~M?fd@B`ALtA",
  },
  {
    athleteId: 1075670,
    date: "2019-11-13T23:00:06Z",
    id: 71170671750,
    name: "Don Quixote Dr",
    segmentId: 12002432,
    rank: 1,
    line: "ccpnEp_kqUk@z@Wn@WvAMdA[zAo@lCUn@_@xA",
  },
  {
    athleteId: 1075670,
    date: "2020-04-25T18:22:17Z",
    id: "2689197347790957000",
    name: "MK Coast TT",
    segmentId: 8860292,
    rank: 1,
    line:
      "oxtnEnhjrUeAxBs@nAUJMA}Ac@yBiBcBoAqDuBgEyCKAMDKFEJALDb@p@`Cf@lEh@|C@VCbABn@@TLj@\\v@lA~AvAnBjCfFTb@AACp@o@nCgA|BiAvByGnNeAfCwBlGu@lCOt@a@zCa@hCmBvGoIhX_A~Bw@nAqAdBkAnBmCvH_CfGaAbCgAbCcAlCu@nCi@lCc@fEmAzESpAI|@G|@AhBB`A^pH@xCIrCCjCLpCrBtL`@zCXzCD|CIpDSpCi@bCwB~FmCzKi@pCk@dC_AtBq@dCYnCAxCCf@}@jHWjC?NK^[`EOpCC|CHbDZ~Cn@tCx@rCt@|B~ClGp@~BBTFxCUnDCtC@zCJrCh@bD`CxLjAtGL~CWnCa@pCe@hC[jCIrCAxCWtCcAzGKjCHlCCpCKbDJbDNbA`@rBV`DP`LR~HC~BOlHJzCh@rCv@rCl@bCr@dCx@|BlDfFz@lCZtC@tC_AhHGpHKnCoB|`@Q~Ck@rHKnC@lCHbD^tCr@fCh@xCVpC@rCErC_@xHItCLbFXjEVdDbArH@xCq@`Ia@vCcAtG]jC]bDqAtK[~CU`DBfDHnC^xCh@lCVrC@jBQzCUxCyBxVq@|Q_@bH{@tRQrCCvCBxCFxCNrCZhRB~CHzCPvC\\pCf@nCj@hChBpGzBnGXjAEmCm@_B_AqDqBaHm@iCYgB_@uCQuCKyCYgM]wMC{C@{CH{C\\cIr@{Rb@qHVqHPwCbByQv@oHD{CQyCsAmHOuCC_CHqC~AkOz@sHTmBpBuMN}AVmFBKCsAaAwGWoCe@gHM}CDwCd@sHHwC@aCIoA_@kEuA{FY}CI}C?}CL{Cj@uH|AgY^gGJsCBkHTsC^iCJcDMuCe@mCcAaCwAsBoA{BeBiGoAoFe@_DIwCHwHCqCc@gV[kCc@oCKsCJmCB_DK_DHqC|@{GVgCFaA@{AJ{CfB_MJ}COoCe@mCo@uCwB{L_@{CMqCBwCHoCTsCIwCc@yBIUyCwFaAcCgBsGe@kCMmCBeDf@cJVqCj@}E\\aCLqEV{Cp@cCtAyDp@wCvAeHn@eCt@}BnB_Gh@eCHo@F{B?uCOqCYoCaAaGiAwGSmC?cDHmC?oCKmCUcD?aDPeDb@kCl@mChA{Gj@iCz@cC`AuBdAcC~BaG`C{FbAoCDIJAFBTXD?FCRYjAwBx@aCVaA`A}BbDwKp@oCp@cBzAyFJo@h@cBPeAXgAX_BRa@lDcKVwAv@yBlCwF",
  },
  {
    athleteId: 1075670,
    date: "2019-09-02T14:41:36Z",
    id: 66941974567,
    name: "Lake Tahoe Loop -State Line to Lake Pkwy",
    segmentId: 9675572,
    rank: 1,
    line:
      "eexlFffa{U|BvAlJrF|G`E`Av@|BxBnB`Dt@zAt@fB`C`HzCrI|AzE~CbJ~Oje@dAvDbC`Mr@`DlBrJRnAV`D@l@?HMRD?FF@F?fACtAS`CWvBIrBAvABvADfAXlClCzQd@bBN`@h@jAf@x@h@p@z@v@n@d@v@\\t@XZHdAN`BDpFIdDB`FEbDFrC@tADdCJpBNjC`@f@NpB\\dCn@dBj@xBz@zAr@xBjAdBfAvCvBdBzAdAbA`BhBtA~ArAfB~AbCrC~EjAhBd@~@zBxDhCdEhExHxEbI|DfHfAfBrAbCrDlGn@`AjArBfBrCzBhE`DlFtBvDjIrNzAfCt@fA|@hB`@fAl@`CDb@Ab@ENO\\eAjAiDlEeAxA{AdCmA`C{ExKmC|FmAjBkCjDc@n@cBvBSZw@jB]tAQhAqAnKsApLoAlJeBxKs@vEc@xBe@~Aa@bA_AbBIVa@x@mG`KuCjESXaA`Ai@`@uAl@_ALsKn@{CVo@Hy@Vi@^e@b@{@jAo@v@mGzIk@hA_@tAQzAKhCSxCOnF]dEUdBOx@uAbFeAtESzACxA@vAFdAjBvVp@nJfBbTn@~GFzAAr@Gp@YbBs@tC[dBKt@KnAAp@?j@HhBPtBBdBCz@_@nDGv@@v@HdB?x@KfIMzEIh@Kd@a@hA[t@]n@i@v@i@h@Ud@IZEr@Bt@Lr@lApDLd@Nz@H`APdGPdCXbBRvAVbCf@zD?f@Gb@M`B@`@GvA?tATzC@lBKbAQr@u@dBW\\[V]Pq@Pa@Bw@?y@AsAKgC@}@DkATgBp@aCr@oANmAFgCQ{AEYBgA@yARyABUAgAa@eEcAk@IkBMgDe@sB_@yBg@gAO{@QaCq@]CSBc@ToAjAwAp@{Af@o@Z[\\GHCN@NLZbAlAj@`Az@nAPZP`@Lb@Hh@FbA?p@Et@Ov@Ur@Up@Wj@_BhCg@`Ay@vBs@~BKl@?TDRb@hBJh@L|BZbBXn@TTd@ZNPHR@NANIJIAIEu@o@i@s@g@y@m@iAiByEo@{BYu@SYaAoCKOSEKDINCR@\\NrBL~@n@hD^lDFtAANELKHC?MEMQQMQGI?KFCJATBNXd@f@l@Zt@Vx@Th@Zh@LVfAfB`AjAnAzBzBhFr@pBx@pC`@jAv@~A~@zAd@pAZlAPf@bAzBbBzCPf@Dh@?j@Ip@G`CCd@WvAIv@ObDAfADr@Pz@^bA|@xBVhABj@Ah@Kf@Od@Q`@o@x@S`@o@x@U`@e@hAWtAo@nGGl@Mj@c@pAe@lAiBxDuC|E[PSZYT{BtD[HmAl@uAj@yEzBo@Ho@AWC}@WeA[i@Yo@g@m@u@Wa@y@gBSYM[e@o@OOYQiD}Aq@a@u@m@_@c@m@w@iAsAs@cAm@iASg@e@gBU_Bc@eB[w@y@gBe@o@oAsAq@_A{CgDwBqCu@eAs@iAgCsEqA{ByAiB{@{@y@s@gAy@uAy@gCkBkAm@sA]w@O[Cy@CmDDiCTeIlAgDRyAR}ALqCZgBVsATi@T_@VcBbBw@n@uA|@wAz@q@Xo@`@{A`AgA`Aa@b@m@~@yDjHc@l@g@f@q@^[J[DsEL_AH]F}@T{Aj@_@R{@p@sAtAq@|@i@dAoAnCwA`CmBtCi@p@UTWP[L[H[@_@A]GqGsB}@Q_@C]@y@H[FqAf@w@b@[Rq@n@m@|@iAfCi@bAo@x@YX[T}@b@a@Ha@Fa@@aAEcAOa@O{@k@s@q@U]Sa@q@oBSc@W_@Y[[W]S_@Ma@IeAEoDNiAJiARcA`@{@p@W`@i@dAU\\WZs@f@s@XsCbAs@JwCLs@RcDdBsA~@cBtAmAt@}An@yD~@qA`@g@TqAx@e@`@g@j@oDvF{CtDoEbFc@ZWLKDY?YCWIg@YiByAYQi@SYKs@M_AE_AFg@HgDx@{DfA}@Po@Te@Tw@h@g@l@kBlBu@~@eCnCYb@KZKl@Et@Dv@\\nB@r@?v@OvAm@pDKf@Od@U`@Y`@_@Xa@LWBc@?wA]]Ea@Ds@^OPKVIXEz@QpFIjAKd@O^WVYPYHYAYMSSyAeB{EaFcGcHc@a@g@YyCmAwEyA{@OgCKy@Ig@IqBi@g@K{BMi@GwBo@{@a@u@m@s@o@eKcKu@m@oBoAw@m@eBiB{CuDYU_@Ka@?OD_@TY^KPQl@Y`BSt@MVa@f@SJk@Jk@BuABi@Le@Va@\\]f@c@fASt@Iv@?\\J|AZbCdB~KLdAHhA?lAEd@QfAM^OZg@j@UNWLiHxBaALUAk@GSGe@Wa@a@}B}Dq@y@uA{@qBy@_Ao@_@]c@k@sAoBu@y@]W_Aa@cBa@c@SYSoA{A{@oAkAcAk@[WKw@O}@EkCBa@GMEm@k@iB_C}@cAoAaA_Ag@[M{@Ua@Es@GwBCyK?_BE]C]Eu@WwFyBmASc@A_@Dg@L_Ah@}@h@i@`@w@j@_@Pq@h@w@d@w@`@eDzBcB`AsAp@}ChBeCpAmB~@aCpAaK~EaCpAq@b@kAjAkAvA_E`GqCnDmD`EuDzDcApAm@fAg@hAOd@_@`BOnAGz@EdBJzK@pBEnBI~BIz@g@`DWpAu@bCsAdDmChHq@fCe@bCaAbE_@jAk@tAs@fAc@d@gCrB}@l@mF|E]`@]h@Wp@St@WvAKxB?z@XxGEfB[zBQn@Un@Yj@]f@]f@mC~C[b@s@lAcAzBeBfFyA|Dg@bAk@|@eApAo@n@u@h@{BlAsClAoE|BuB`AwGfCiChAaAd@STGJB`CG\\GH_@AY@GBMG@?E@GCEK?BMECOGOIGYg@IEM?sAb@mAf@yKfEsFdB}DtAm@V}@h@k@ToOlE{@LgABaDKgB@wBH{BGmDWuC[_Dk@}ASmBIoECaBGsBUgC_@{Cq@}Bu@{@]yAs@gEwBuAa@iASkDYiAM_CQeAQ_@Me@[{@{@i@s@{A_BsBcBwB}AoBgAiAg@iAWy@Ew@De@FwA^eBh@cAPc@@iACcDYq@?s@Jk@XYTSZe@`A]lA]x@Sb@Y^i@h@]T}@h@}@`@}@\\_Bf@eCj@{Cb@aEZuAVaATmE~AoA`@u@Ps@Hw@C_Cq@gFmB}CeAmAi@o@_@{@o@}AyAmC{CcOuOuAeAeBkAaCuAmEwBcC_AcAe@mC{@sBk@{@QoAMqA@mAJkATqBf@{Cl@iANcAD_A?eAEu@KoCw@uAq@c@_@i@k@q@k@i@m@o@_Am@eA}AcCYo@o@iBg@_CYaBm@wEi@mC]gAo@{AiAqBg@s@i@o@eA_AiAs@aAc@u@Sy@MmAEoABi@F}@PyBn@g@H}@HoABwE?_BBsBCgIEuBE}AGeBMwDc@kGaAwHeBeHgBuImAiAKgAGoAB]F[Lg@VwBbBm@Rk@F]?[CYGa@Ug@g@QUuAoCoAqBoAaBs@y@cBwBqImLkAuAa@_@qEwCs@m@i@q@mBoC_EiFkAgBaAiBsBuE}DuIgAiBk@w@y@{@gAw@mG}CyAaAeA_As@{@o@_Aa@s@s@}Ac@qA{@_DaAeDeAgEe@yAi@sAiEuIq@mAkA}AqByBmBkB{AcBg@q@w@mAu@aBk@wAK_@oAkDcD}J_AqDUqAYaCQuC]{QK{BQaBKu@q@yCw@}B]s@w@sAY_@y@_AgAeAyC_Cq@o@s@}@s@gAo@{A[}@[kAoBuIW{@_@w@i@s@m@m@[Qw@]_@I}@G_DDa@Aa@G_@I_@O]SY]a@oAKi@UsDIi@Qg@Sc@u@_A][sBoA]Ma@GoCj@{AL{CJwAI_BWyCo@}Ay@s@[oDYkAOmAYiAa@m@Yi@_@c@c@uDoFoAqBa@iAMg@K_AUwCGk@Mi@Og@c@q@W_@q@a@c@Me@KiDK[Cs@My@WcD_B{@[s@QsDa@uCQmCScDg@sIwAwAa@_Bw@o@UeAU_AIe@?qGBqFCwFDa@Eu@Yq@k@[g@eCgFyAgDkEcJa@iA[mASkBGiBDaRHaBVmBx@iDNs@H_B?qAEy@Ky@Uu@Yo@cAqAw@w@W_@i@aAmAoCg@_AU]c@e@WUe@[oEmBkA_@UEsACg@BoHx@qBPoHRiA@g@Ag@Ce@ISIy@a@a@a@_@c@e@}@So@WeAIo@Eq@KkOOcEWcCU_Bk@sC]iAq@gBkAeCoA_Cs@kA}BcDsD_FeA}A]cAMq@Iq@?gADeApAiPLyBfAsMf@aFf@cHB}@@cDDy@TeAL_@P[j@o@`BoA\\i@P]L_@Jq@B_@?oAK{@iBoK}BkLs@_EEe@Cg@@kAR_BLg@x@eBzBgEZy@XuApAwTNsEj@uGD{ABaDHgDNoBXkBx@cDLWROFIT}@h@cBr@yCn@kDHIXIfAHHCTc@?IGOA^QTQFe@CE?EBAPJdACDGBHHAFED@ILOCKBBKa@CU@k@G[TmCbBoIrAgG^sAfAyCbAmBz@kAxAyAx@o@lM}FfCwAz@m@rAqA`AiAf@y@pAqC`@iAd@}ATaAZoB|@gE`@oCNyAF}BGgBMaAUcAaBsEs@wAYy@Wg@[a@a@[g@Wu@S}@IoD@gCEkA?mAIaAMiB_@uEgAsCk@cDw@mCi@cCm@{D{@s@ImCBi@AUGk@Si@[qA_Ak@YWIs@KeCOeE]w@Ou@]s@g@{CsDm@m@q@e@s@_@YIiDs@[I[QoA{@mCsCo@i@q@a@qCuAk@a@QUi@iAiFwMUy@Ki@K}@KwAC_A@aAn@mNTuDByABgCEkEW}IMkBW{AS}@E]Fe@Vw@Fy@g@kNAwDP}HV}Dh@kEv@qEb@mB^}ApAiEz@aCrDeJfCyGbBoFxAsFfAcGFQd@uBVeBh@yCLaAdCwMbAeGXkAr@uEjAcGVaBDi@rAoG~A}It@yDlA_Hl@kCT_Bh@iC|BoM|@oEJ}@Lo@b@eBFi@l@yCf@}CZqAdAaGVkAj@kDDM^kBFm@n@uCxAmDfAwB~@oAdAoAj@c@pA}@rBgAnAc@fD{@zEwAVQHINWL]NQDAl@Dj@?`ACjDq@`AIb@?zBVrCBb@Hb@NpAt@^Pr@TrAV^Fp@@l@Az@IdF{@p@[`@Yj@o@^i@rHcL~@gBlAqCp@gAVWd@]v@_@j@OvAQvBMvEc@n@En@?n@D~@LjA\\dAh@jA|@xClCn@\\f@Fd@CJEf@Q~Ay@l@MjAAnCHxEOt@@b@Bd@Fb@Jr@Zl@`@nB`Bt@^j@Nh@Bh@ApAUzA]~@IjCEt@Bl@Jh@Rn@f@bAbA`@\\f@Xx@Zr@Nb@D|EHj@?~@Mh@QfPwHtAi@|@YhDy@f@InAY|JoBrCm@lF_AjAG|A@|Ir@lDT^?^E`Ca@`@C`@@`@D`@HlCr@x@Lf@@b@AfB[d@Cn@@lBPf@@l@Ad@C^I~Ac@|@Sx@Gp@?|@Gn@Ol@UzCkB`C_Ap@QtASxBWpCSzAWjA_@n@YvFcDj@[\\Mj@Qb@K~AIp@KzCkA~@Q`@At@Bd@FXHv@^`KhIl@f@t@`@v@Xz@RjDRjANh@JtAb@hB~@lB~AlApApA`CrAjCp@~@x@~@vAdAbAh@fAb@^J|@LtAFnAChLmAtACp@DnATj@LZLlA^`B^v@Jz@HjBDfAA|BS~MgCvBk@`A]nAo@|@k@f@a@t@m@`@c@fAsAp@s@v@eAr@i@r@Sb@GNArJJxAGd@ItA]fBu@t@Ql@E|AFhA?v@Gf@O`@SpB{Aj@Mb@?f@Nn@d@\\RVHh@Hb@?j@Ml@SpD_BRM\\OPEtAy@nAg@j@Op@G`@@\\J\\PZXZ^^r@nAnBzAjCtAlBb@f@~DhDfDdC`BvAt@h@rC|BfAz@xA`A~At@|@ZhBf@`BZdAJl@@`GFt@?v@Cx@MrA_@rAs@hBwA\\Qz@YbFcAp@EnBCbBUtDy@bDeA~CoAbCmArAy@TSf@YnB{ArBqAnB_An@WtA[pB[ZEpCIvHKj@Gp@Oh@WTSb@g@Zm@L]Jk@F{@N}@Na@l@_An@o@VKtByA\\UXMz@k@rAo@v@UZGjCSxEMbCKbAK`@I|@_@x@m@b@_@z@aA\\e@t@mAlAwBtD{HZaARg@z@_BL[pAqBnD{Dz@gANYRi@P}@VkBTs@vFmMl@mAh@w@dAgAdAq@bA]v@Qx@Gn@?rKn@~BZzE~@t@Fx@?vAOx@Sz@[xAu@~@Y`@IbAC`@BbAN`A\\z@j@rB`B\\R`A^bAPjCF`@FbAX^Rz@n@x@x@lB|BnAdBlAjBn@lAvA|C~DzId@pA\\vAJj@NxABj@?zAU|EE`C@vAN`F?bCQ|FUzBkA~IGrBDlADf@XnB\\fAb@bAhB~C`@hAZnAHf@LnANrCXdBX|@nApCj@zAx@|CZxA^lDLrBBx@@vAEhM@|@Fz@Jx@VnA^hAd@~@j@t@^`@v@h@f@Th@P~@Pj@Bj@?fDOlHOjAGfAUn@QrB}@vHqDn@YjA[`BWvNcAj@CdAFj@Jl@P`CpAh@Tj@Nj@Hf@@zCGp@Fl@N^P|@n@z@bAdAzAd@d@b@X^N\\Jh@Ht@Dx@GREh@O\\ObCwAv@[l@Mz@Mn@E^?n@Fp@LjDlA~@Nz@Bb@A`DY`A?t@D~A\\~AXhCZvAFtC@`AHr@LbAZbCpA`A^fAVhANhEZb@BlBAlGShAHp@Pp@\\j@d@d@l@r@pAxC`JdAhCr@dA\\Zn@`@`@PtA^r@ERGpAk@f@QREvAGlDCzBGjAKjAOfFy@p@Gn@?p@FdAX`Ad@bBdAzAt@l@LfCNv@J^JZNjBjAj@P`@Dd@Ab@Gj@Ub@YX[V_@xAcCj@gAh@s@h@g@l@c@r@[b@Mv@Op@Ez@BnCVp@Bp@Cx@MfEoAxAYtGk@pScD`AKlAGjBCfABrAHrE`@rHx@`DXnB`@jA\\pGnCpDpAhB`@tBNz@B|@?fDKlFKvGQxGWxACfM_@xEGFBHLF@ZULCrA@vBIx@Bv@L`@Pb@RrAdAr@p@bBdBPZf@rATvA@vBUvIe@lGQbBIxAAr@Dr@TjATn@\\n@v@x@l@Zr@RnAF|@?tAI|@O`AU~@]bAe@j@_@j@c@~@}@x@eAb@q@rLuU~BkEx@gAf@g@|@m@f@Wz@[f@Id@Gn@AdBHVDv@TzEbBvAb@tARjADrAEd@Gz@QxAk@bAi@^Yf@c@z@_Ar@eA~AeCjD_GjBwCbFyH~A{BLIPc@P[|B}Dz@oA`@g@n@gA~@qArAyB`CiDlByBjB_BxB_Bz@g@nAo@r@WlC{@xBe@`Hy@hC_@nGeAhEo@hAKhAGdB?`BHt@HZLNAH@rBb@dBf@~An@pCdB|DvBpGvDnG`E`@Z",
  },
  {
    athleteId: 1075670,
    date: "2018-02-17T16:50:34Z",
    id: 35085344620,
    name: "The Most Painful Part of the Pain Cave",
    segmentId: 11058558,
    rank: 1,
    line: "{|qqFtggaSN\\PVpAtAzArARTXh@rAtCRXPb@BXBp@GbAB`ALn@LT\\ZPF^@",
  },
  {
    athleteId: 1075670,
    date: "2016-09-01T21:56:12Z",
    id: 17095894082,
    name: "S High School Sprint",
    segmentId: 4539170,
    rank: 1,
    line: "oyfqFbus_SAd@GLKHe@LmC^q@@_CIsG?",
  },
  {
    athleteId: 1075670,
    date: "2015-01-10T15:52:50Z",
    id: 31046823337,
    name: "Express Ride to the Ride",
    segmentId: 6905390,
    rank: 1,
  },
  {
    athleteId: 1075670,
    date: "2018-11-23T22:06:20Z",
    id: 49910787609,
    name: "Cravens to Santa Monica Sprint",
    segmentId: 8047128,
    rank: 1,
    line: "k}~pErtrxUDcAh@{D|D}]LQFa@GUdAgJDo@As@a@sD",
  },
  {
    athleteId: 1075670,
    date: "2017-09-06T15:46:16Z",
    id: 28864068205,
    name: "Col du Roll (Foothill of Pain)",
    segmentId: 1472146,
    rank: 1,
    line: "ypsqFbfz`SS~@i@j@GbAZl@Lh@Ob@]Nc@LMd@Pf@V^Td@Jp@",
  },
];

export default demoEfforts;
